<?php

use Drupal\Core\Site\Settings;

/**
 * Implements hook_uninstall().
 */
function multiversion_uninstall() {
  \Drupal::state()->delete('multiversion_migration_done');
  \Drupal::service('config.factory')
    ->getEditable('migrate.migration.migrate_users_from_json_to_drupal8')
    ->delete();
  \Drupal::service('config.factory')
    ->getEditable('migrate.migration.migrate_users_from_drupal8_to_json')
    ->delete();
}
